### ISSUE TITLE
Security: Add HTTPS Support

### ISSUE THREAD

**Issue by akiekintveld** [verekia/initializr-website#13]
Currently the website lacks support for HTTPS. Without encryption, content on the webpage can be modified or intercepted for malicious purposes. This leaves people open to attacks such as JavaScript injection and tracking. Modern browsers are also deprecating insecure HTTP for newer features, and many page optimizations will not be present. With the dawn of [Let's Encrypt](https://letsencrypt.org), there really is almost no reason to not support HTTPS.

**Comment by rugk** [comment]
Why you should always use HTTPS (no matter whether the site is static etc.):
* https://doesmysiteneedhttps.com/
* IT security specialist: https://scotthelme.co.uk/still-think-you-dont-need-https/
* Google: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by akiekintveld** [comment]
This appears to be abandoned. Closing.

**Comment by rugk** [comment]
GitHub recently added https support for custom domains.
